### ISSUE TITLE
Change model?

### ISSUE THREAD

**Issue by cre8tions** [legion1581/go2_firmware_tools#1]
Does this mean one could buy the "air" model, and be able to use the features of the "pro" model?  Wondering, because that's a substantial price difference and if this is the case, would be a game changer

**Comment by legion1581** [comment]
This tool unlocks features for AIR/PRO that are available only for the EDU model, such as secondary software development. The AIR model is missing some hardware components like the audio module, UWB module, and belt tensioner. The PRO model is much closer to the EDU model; the only differences are the absence of foot sensors and no NVIDIA payload on the back for heavy calculations.

**Comment by Janphr** [comment]
How important is the UWB module for secondary software development?

**Comment by legion1581** [comment]
Used UWB just a few times during the year, I would say it’s not working that good as advertised
