### ISSUE TITLE
support for 1.1.2 firmware

### ISSUE THREAD

**Issue by gWOLF3** [legion1581/go2_firmware_tools#3]
hi - thanks for this. 

have you or anyone tried yet with latest firmware from unitree - 1.1.2?

**Comment by gWOLF3** [comment]
i'm going to provide an alternate answer to my own question - its possible to downgrade the firmware to 1.1.1 version w/ a rooted rootfs partition, from there you just enable secondary development. there is a discord and wiki w/instructions here: https://wiki.theroboverse.com/en/firmware/root/custom_rootfs

**Comment by legion1581** [comment]
Patching binaries is very resource-consuming. Version 1.1.1 took about one month of my free time, so please do not expect that each new release will be supported :smile:
